### ISSUE TITLE
Update the FAQ docs to include the `Verbose` prop

### ISSUE THREAD

**Issue by ganigeorgiev** [go-pg/pgext#13]
With the latest version, only the failed queries are printed when using `db.AddQueryHook(pgext.DebugHook{})` (this wasn't the case during the go-pg v10beta).

I'd suggest to update the [faq docs](https://pg.uptrace.dev/faq/) to add a note or include the `Verbose` prop.

**Comment by vmihailenco** [comment]
Done.
